<?php

/* 
* Implements hook_ctools_plugin_directory -
* This lets ctools know to scan my module for a content_type plugin file
* Detailed docks in ctools/ctools.api.php 
*/ 
function ajax_link_ctools_plugin_directory($owner, $plugin_type) {
  // we'll be nice and limit scandir() calls
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}

/**
 * Implements hook_menu().
 *a/
function ajax_link_menu() {
  $items = array();
global $user;
  echo "Last login: ".format_date($user->login,'small');

/**
 * Callback function that displays a simple Ajax powered link.
 */
function ajax_link_page() {
  return array(
    

/**
 * Implements hook_menu().
 *a/
function ajax_link_menu() {
  $items = array();
global $user;
  echo "Last login: ".format_date($user->login,'small');

/**
 * Callback function that displays a simple Ajax powered link.
 
   }
}
}
      ),
    );
}

/**
 * Ajax callback to display the current time.
 */ 
    // Menu 'page callback' and #ajax['callback'] functions are supposed to
    // return render arrays. If returning an Ajax commands array, it must be
    // encapsulated in a render array structure.
   
  }
}
}